[build]
publish = "public"
command = "./stackbit-build.sh"

  [build.environment]
  HUGO_VERSION = "0.47"

[[redirects]]
  from = "/*"
  to = "/db"
  status = 200
  force = false
  conditions = {Role = ["admin"]}
      
[[redirects]]
  from = "/*"
  to = "/login"
  status = 302
